# Generated by Django 2.1.4 on 2018-12-16 18:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.AddField(
            model_name='article',
            name='content1',
            field=models.TextField(default='d', verbose_name='문단1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='content2',
            field=models.TextField(default='d', verbose_name='문단2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='content3',
            field=models.TextField(default='d', verbose_name='문단3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='graph',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='그래프'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='map',
            field=models.TextField(default=1, verbose_name='지도'),
            preserve_default=False,
        ),
    ]
